// Frozen allowlists derived from public chain history.
//
// Some contracts cannot answer "does this wallet have one?" — the v1
// TalentFactory on Celo only maps token → talent, never talent → token, so a
// per-wallet read is impossible there. Where the underlying set is closed
// (that factory has been dormant since July 2023), the honest substitute is
// the creation history itself, shipped as data and regenerated by
// scripts/build-talent-token-allowlist.mjs.
//
// This is public data, unlike the Talent-database snapshots: anyone can re-run
// the generator and get the same list. It is bundled rather than fetched — 564
// addresses is small enough that a network round-trip would cost more than it
// saves.

import talentTokenLaunched from '../../spec/allowlists/talent-token-launched.json'
import type { Allowlist, BadgeInput } from './types'

export const allowlists: Record<string, Allowlist> = {
  'talent-token-launched': talentTokenLaunched as Allowlist,
}

export function readAllowlistBadge(name: string, address: string): BadgeInput {
  const list = allowlists[name]
  if (!list) return { status: 'unavailable', reason: `unknown allowlist: ${name}` }
  const wanted = address.toLowerCase()
  return { status: 'ok', earned: list.talents.includes(wanted) }
}
