import type { Metadata } from 'next'
import Link from 'next/link'
import { badgeDefinitions } from '@/lib/badges'
import { badgeSourceDetail, describeBadgeCheck } from '@/lib/badge-reference'
import { snapshotMeta } from '@/lib/snapshots'
import { credentialsPath } from '@/lib/routes'
import { PingDot } from '@/components/motion/ping-dot'
import { FadeRise } from '@/components/motion/fade-rise'

export const metadata: Metadata = {
  title: 'Badges — Open Builder Score',
  description:
    'Every badge shown beside an Open Builder Score: what it means and exactly how it is checked. Badges carry no points.',
}

export default function BadgesPage() {
  return (
    <main className="mx-auto w-full max-w-3xl flex-1 px-4 py-12 flex flex-col gap-10">
      <FadeRise className="flex flex-col gap-2">
        <h1 className="font-heading text-xl font-normal">Badges</h1>
        <p className="text-base text-muted-foreground">
          Achievements shown beside a score without entering it. All{' '}
          <span className="font-mono tabular-nums">{badgeDefinitions.length}</span> carry zero
          points, so no badge can move a total or change what an attestation says. Points come from{' '}
          <Link href={credentialsPath()} className="underline hover:text-foreground">
            credentials
          </Link>{' '}
          instead.
        </p>
        {snapshotMeta.generated_at && (
          <p className="text-sm text-muted-foreground/70">
            The export behind the snapshot badges is dated{' '}
            <span className="font-mono">{snapshotMeta.generated_at}</span>, generated by{' '}
            <span className="font-mono">{snapshotMeta.source}</span>.
          </p>
        )}
      </FadeRise>

      <FadeRise whileInView>
        <section className="flex flex-col gap-3">
          <div className="flex items-baseline justify-between gap-2">
            <h2 className="flex items-center gap-2.5 font-mono text-xs uppercase tracking-[0.18em] text-muted-foreground">
              <PingDot settled /> How each one is checked
            </h2>
            <span className="font-mono text-xs uppercase tracking-[0.18em] text-muted-foreground/70">
              {badgeDefinitions.length} badges
            </span>
          </div>
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
            {badgeDefinitions.map((badge) => (
              <article
                key={badge.slug}
                id={badge.slug}
                className="flex scroll-mt-16 flex-col gap-1 rounded-lg border bg-card p-4 shadow-xs target:ring-1 target:ring-success/60 dark:bg-card/50"
              >
                <h3 className="text-base font-medium">{badge.name}</h3>
                <p className="text-sm text-muted-foreground">{badge.description}</p>
                <p className="font-mono text-sm text-muted-foreground/80">
                  {badgeSourceDetail(badge)}
                </p>
                <p className="text-sm text-muted-foreground">{describeBadgeCheck(badge)}</p>
                {badge.notes && <p className="text-sm text-muted-foreground/80">{badge.notes}</p>}
              </article>
            ))}
          </div>
        </section>
      </FadeRise>
    </main>
  )
}
